/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wfh_emplos_platform_CrossPlatformWindow */

#ifndef _Included_com_wfh_emplos_platform_CrossPlatformWindow
#define _Included_com_wfh_emplos_platform_CrossPlatformWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wfh_emplos_platform_CrossPlatformWindow
 * Method:    getActiveWindow
 * Signature: ()Lcom/wfh/emplos/platform/Window;
 */
JNIEXPORT jobject JNICALL Java_com_wfh_emplos_platform_CrossPlatformWindow_getActiveWindow
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
